# Introduction to Numpy

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.

## 1. Numpy Basics
### 1.1 Numpy Array
Numpy’s array class is called ndarray. It is also known by the alias array. Lets create a dummy array of 'float' type, and print it.

In [2]:
import numpy as np
a=np.array([[1,2],[3,4]],dtype='float')

# Print the array
print(a)

[[ 1.  2.]
 [ 3.  4.]]


### 1.2 Basic Operations
Following are some simple operations in numpy

In [11]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print(b)

# Subtraction
c = a-b
print(c)

# Squaring
print(b**2)

# Sinusoid
print(10*np.sin(a))

# Logical
print(a<35)

# Element wise product
print(a*b)

# dot product
print(np.dot(b,a))

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[  0  30  80 150]
260


### 1.3 Indexing, Slicing and Iterating

In [12]:
a = np.arange(10)**3
print(a)

# Print an index
print(a[2])

# Print a slice
print(a[2:5])

# Looping
for i in a:
    print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


### 1.4 Python functions

In [18]:
def hello(name, likes_GOT=True):
    if likes_GOT:
        print 'YO, %s, Jon Snow rocks!!!' % name.upper()
    else:
        print 'I dont know you, %s, go to hell!!!' % name

hello('Bharat') # Prints "Hello, *name*"
hello('Udyan', likes_GOT=False)  # Prints "HELLO, *name*!"

YO, BHARAT, Jon Snow rocks!!!
I dont know you, Udyan, go to hell!!!


### 1.5 Python classes

In [29]:
class Greeter(object):
    
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable
        
    # Instance method
    def greet(self, likes_GOT=True):
        if likes_GOT:
            print 'YO, %s, Told ya it was good.' % self.name.upper()
        else:
            print '%s, you even real!!!' % self.name
        
        
g = Greeter('Udyan')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(likes_GOT=False)   # Call an instance method; prints "HELLO, FRED!"

YO, UDYAN, Told ya it was good.
Udyan, you even real!!!


<b> Well I guess this should get you going.</b> But if you need anything just take a look at:

Python: https://docs.python.org/3/tutorial/

numpy : https://docs.scipy.org/doc/numpy-dev/user/quickstart.html